<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectPartnerName</name>
   <tag></tag>
   <elementGuidId>b31bbac4-16a1-4993-81c5-c1416bbac06a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//common-select2[@formname='partnerName']//ngx-select-dropdown</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
