<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>scrollToTable</name>
   <tag></tag>
   <elementGuidId>b4f2c3f9-d1e1-442f-812a-3b4eb699884b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
