<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbWithCost</name>
   <tag></tag>
   <elementGuidId>682694a6-a53a-4d22-b353-20da6623542f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-checkbox[@formcontrolname=&quot;withCost&quot;]/div/div[@role=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
