<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnClosePreview</name>
   <tag></tag>
   <elementGuidId>b07791dc-867c-4ee1-9362-e3aa645fb23e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[3]/div[4]/div[1]/mat-dialog-container[1]/app-preview-export-list[1]/h2[1]/button[1]/i[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
