<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpEducation</name>
   <tag></tag>
   <elementGuidId>e5c684e8-8056-457a-87dd-5433b4d2ab63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/app-pages[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/app-e-mr-sow-create[1]/app-e-mr-sow-create-form[1]/form[1]/div[1]/div[2]/div[5]/div[1]/div[1]/textarea[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
