<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectIDCard</name>
   <tag></tag>
   <elementGuidId>8b7ef2f7-3c83-45eb-96c3-b6c30c60a98e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/app-pages[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/app-e-mr-sow-create[1]/app-e-mr-sow-create-form[1]/form[1]/div[1]/div[2]/mat-checkbox[1]/label[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
