<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpMaxSquadLimit8</name>
   <tag></tag>
   <elementGuidId>2053e6a7-0a20-44f7-b9c1-ee6b6c1d5d2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/app-main[1]/nz-layout[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/app-settings[1]/nz-card[1]/div[1]/div[2]/app-squad-limitation[1]/nz-spin[1]/div[1]/div[1]/div[2]/div[8]/nz-card[1]/div[1]/div[1]/div[5]/div[1]/div[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
