<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpMaxSquadLimit5</name>
   <tag></tag>
   <elementGuidId>82d7e404-b059-4ed6-befc-f8db5e3b4f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/app-main[1]/nz-layout[1]/nz-layout[1]/nz-layout[1]/nz-content[1]/app-settings[1]/nz-card[1]/div[1]/div[2]/app-squad-limitation[1]/nz-spin[1]/div[1]/div[1]/div[2]/div[5]/nz-card[1]/div[1]/div[1]/div[5]/div[1]/div[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
