<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectICCIDImageCheck</name>
   <tag></tag>
   <elementGuidId>38408278-cdd8-4587-8d28-2f3bf2ddd340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdown[@formcontrolname=&quot;iccidImageCheckStatus&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
